networks:
  median-network:
    driver: bridge

services:
  db-postgres:
    image: postgres:16.3
    container_name: median-db-postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
    networks:
      - median-network

volumes:
  postgres:
    driver: local
